---
- name: Palo configuration
  hosts: palo
  connection: local
  ignore_errors: true
  vars:
    provider:
      ip_address: "{{ ip_address }}"
      api_key: "{{ api_key }}"
  tasks:
    - name: Include User Variables
      ansible.builtin.include_vars: vars/config.yml
    - name: Include IP vars
      ansible.builtin.include_vars: vars/ips.yml
    - name: Include Service vars
      ansible.builtin.include_vars: vars/services.yml

    # - name: Show Facts
    #   ansible.builtin.debug:
    #     var: "{{update_os}}, {{logging}}"

    # - name: Pause until for commit verification
    #   ansible.builtin.pause:
    # - name: Print configs
    #   ansible.builtin.debug:
    #     msg:
    #       Update OS: "{{ update_os }}"
    #       Update Other: "{{ update_other }}"
    #       Initial Interface: "{{ config_initial_interface }}"
    #       Initial Groups: "{{ config_initial_groups }}"
    #       Logging: "{{ config_logging }}"
    #       Initial Rules: "{{ config_initial_rules }}"
    #       PANOS Version: "{{ panos_version }}"
    #       # IP Range: "{{ ip_range }}"
    #       # Network: "{{ ip_range_mask }}"
    #       Wazuh: "{{ wazuh }}"
    #       Wazuh Port: "{{ wazuh_port }}"

    # - name: Add Groups
    #   ansible.builtin.import_tasks:
    #     palo/tasks/objects/address.yml
    # - name: Add Tags
    #   ansible.builtin.import_tasks:
    #     palo/tasks/objects/tags.yml

    # - name: Update PAN-OS
      # ansible.builtin.import_tasks: palo/tasks/updates/os_update.yml

    - name: Update AV to latest version
      ansible.builtin.import_tasks: palo/tasks/updates/av_update.yml

    - name: Update content to latest version
      ansible.builtin.import_tasks: palo/tasks/updates/content_update.yml

    - name: Update wildfire to latest version
      ansible.builtin.import_tasks: palo/tasks/updates/wildfire_update.yml

    - name: Update PanOS to latest version
      ansible.builtin.import_tasks: palo/tasks/updates/os_update.yml

    # - name: Add addresses
      # ansible.builtin.import_tasks: palo/tasks/objects/address.yml

    # - name: Add profiles
    #   ansible.builtin.import_tasks: palo/tasks/objects/profiles.yml

    # - name: Add services
    #   ansible.builtin.import_tasks: palo/tasks/objects/service.yml


    # Firewall rules
    - name: Add CCDC firewall Rules
      ansible.builtin.import_tasks: palo/tasks/rules/palo-rules.yml
    #   when: config_initial_rules == "y"

    - name: Commit rule changes
      ansible.builtin.import_tasks: palo/tasks/commit.yml
    #   when: config_initial_rules == "y"

  handlers:
    - name: Wait for System Information
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: show system info
      register: system_info
      until: system_info is not failed
      retries: 200
      delay: 2
      listen: reboot

    - name: Update System Info
      ansible.builtin.set_fact:
        system_info_json: "{{ system_info.stdout | from_json }}"
      listen: reboot

    - name: Update Software Version
      ansible.builtin.set_fact:
        sw_version: "{{ system_info_json.response.result.system['sw-version'] }}"
      listen: reboot

    - name: Display Current Software version
      ansible.builtin.debug:
        msg: "Current software version is: {{ sw_version }}"
      listen: reboot
