---
- name: Inbound-block-sql
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-sql
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [any]
    destination_ip: [any]
    application: [mysql, postgres, mongodb]
    action: deny
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical]

- name: Inbound-block-vmware
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-vmware
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [any]
    destination_ip: [esx]
    application: [vmware, vmware-update, vmware-view]
    action: deny
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical]
    disabled: true

- name: Inbound block active directory
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-dc
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: [any]
    application: [ldap, kerberos, ms-ds-smbv2, ms-ds-smbv3, ms-ds-smb-base, active-directory, msrpc]
    action: deny
    group_profile: security
    location: after
    existing_rule: inbound-vmware
    log_start: true
    log_end: true
    tag_name: [Critical]
    

- name: Allow DC access to DNS
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: outbound-dc-dns
    source_zone: [lan]
    source_ip: ["{{ local_dns }}"]
    destination_zone: [wan]
    destination_ip: [1.1.1.1]
    application: [dns]
    action: allow
    group_profile: security
    location: after
    existing_rule: inbound-vmware
    log_start: true
    log_end: true
    tag_name: [Critical]


# Allow all traffic
- name: Allow all traffic in
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-all
    source_zone: [any]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: [any]
    application: [any]
    action: allow
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical, ALLOW ALL]

- name: Allow web outbound
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: outbound-web
    source_zone: [lan]
    source_ip: [any]
    destination_zone: [wan]
    destination_ip: [any]
    application: [web-browsing, ssl]
    action: allow
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical]

- name: Block DNS outbound
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: outbound-dns
    source_zone: [any]
    source_ip: [any]
    destination_zone: [wan]
    destination_ip: [any]
    application: [dns]
    action: deny
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical]

- name: Allow all traffic out
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: outbound-all
    source_zone: [lan]
    source_ip: [any]
    destination_zone: [any]
    destination_ip: [any]
    application: [any]
    action: allow
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical, ALLOW ALL]

- name: Add windows server rules
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: lan-winsrv
    source_zone: [lan]
    source_ip: [windows]
    destination_zone: [winsrv]
    destination_ip: [winsrv]
    application: [winsrv-apps]
    action: allow
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical]

- name: Add outbound block rule
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: outbound-block-all
    source_zone: [any]
    source_ip: [lan]
    destination_zone: [any]
    destination_ip: [any]
    application: [any]
    action: deny
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical, BLOCK ALL]

- name: Add windows WAN block server rules
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: wan-win-srv
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [any]
    destination_ip: ["{{ windc }}"]
    application: [winsrv-apps]
    action: deny
    location: before
    existing_rule: outbound-dns
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical]

- name: Add inbound block rule
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-block-all
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: [any]
    application: [any]
    action: deny
    group_profile: security
    log_start: true
    log_end: true
    tag_name: [Critical, BLOCK ALL]

# Safety rule
- name: Inbound safety
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: inbound-safety
    source_zone: [wan]
    source_ip: [any]
    destination_zone: [lan]
    destination_ip: [1.1.1.1]
    action: deny
    group_profile: security
    disabled: true
    location: before
    existing_rule: inbound-all
    log_start: true
    log_end: true
    tag_name: [Critical]

# - name: Set initial rules as done
#   set_fact:
#     config_initial_rules: "n"
#     cacheable: true
